#!/usr/bin/env bash
# This script installs a nginx server

sudo apt-get update
sudo apt-get install nginx -y
sudo apt-get install nginx-extras -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo systemctl restart nginx
