#!/usr/bin/env bash
# a script that transfers a file from a client to a server

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

path=$1
ip=$2
username=$3
p_key=$4

scp -i "$p_key" "$path" "$username"@"$ip":~/
