#!/usr/bin/env bash
# This script does some pretty things

pid=$$
echo $pid > /var/run/myscript.pid

function handle_sigterm()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit 0
}

function handle_sigint()
{
	echo "Y U no love me?!"
	exit 0
}

function handle_sigquit()
{
	rm /var/run/myscript.pid
	exit 0
}

trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

while ((1)); do
	echo "To infinity and beyond"
	sleep 2
done
