#!/usr/bin/env bash
# This script displays some strings

function handle_sigterm()
{
	echo "I am invincible!!!"
}

trap 'handle_sigterm' SIGTERM

while ((1)); do
	echo "To infinity and beyond"
	sleep 2
done
