#!/usr/bin/env bash
# This script displays "Best School" 10 times
#+ and "Hi" for the 9th iteration

i=1
while ((i < 10)); do
       if [ $i -eq 9 ]
       then
	       echo "Best School"
	       echo "Hi"
       fi

       echo "Best School"
       ((i++))
done
